module.exports = require('../utils/pluginRules').with('jsx-a11y', {
  'accessible-emoji': 'warn',
  'alt-text': 'warn',
  'anchor-has-content': 'warn',
  'aria-activedescendant-has-tabindex': 'warn',
  'aria-props': 'warn',
  'aria-proptypes': 'warn',
  'aria-role': 'warn',
  'aria-unsupported-elements': 'warn',
  'heading-has-content': 'warn',
  'href-no-hash': 'warn',
  'iframe-has-title': 'warn',
  'img-redundant-alt': 'warn',
  'no-access-key': 'warn',
  'no-distracting-elements': 'warn',
  'no-redundant-roles': 'warn',
  'role-has-required-aria-props': 'warn',
  'role-supports-aria-props': 'warn',
  'scope': 'warn',
});
