module.exports = require('../utils/pluginRules')
  .with('unicorn', {
    'catch-error-name': ['error', { name: 'err' }],
    'custom-error-definition': 'error',
    'error-message': 'error',
    'escape-case': 'error',
    'explicit-length-check': 'off',
    'filename-case': 'off',
    'import-index': 'off',
    'new-for-builtins': 'warn',
    'no-abusive-eslint-disable': 'warn',
    'no-array-instanceof': 'error',
    'no-console-spaces': 'error',
    'no-fn-reference-in-iterator': 'warn',
    'no-for-loop': 'warn',
    'no-hex-escape': 'error',
    'no-new-buffer': 'error',
    'no-process-exit': 'off',
    'no-unreadable-array-destructuring': 'off',
    'no-unsafe-regex': 'warn',
    'no-unused-properties': 'off',
    'no-zero-fractions': 'error',
    'number-literal-case': 'error',
    'prefer-add-event-listener': 'warn',
    'prefer-exponentiation-operator': 'off',
    'prefer-includes': 'error',
    'prefer-node-append': 'warn',
    'prefer-node-remove': 'warn',
    'prefer-query-selector': 'warn',
    'prefer-spread': 'error',
    'prefer-starts-ends-with': 'error',
    'prefer-text-content': 'warn',
    'prefer-type-error': 'error',
    'prevent-abbreviations': 'off',
    'regex-shorthand': 'warn',
    'throw-new-error': 'off',
  });
