module.exports = require('../utils/pluginRules')
  .with('unicorn', {
    'catch-error-name': ['error', { name: 'err' }],
    'custom-error-definition': 'error',
    'escape-case': 'error',
    'explicit-length-check': 'off',
    'filename-case': 'off',
    'import-index': 'off',
    'new-for-builtins': 'warn',
    'no-abusive-eslint-disable': 'warn',
    'no-array-instanceof': 'error',
    'no-fn-reference-in-iterator': 'warn',
    'no-hex-escape': 'error',
    'no-new-buffer': 'error',
    'no-process-exit': 'off',
    'number-literal-case': 'error',
    'prefer-starts-ends-with': 'error',
    'prefer-type-error': 'error',
    'regex-shorthand': 'warn',
    'throw-new-error': 'off',
  });
